### ISSUE TITLE
Move sometimes not uploaded

### ISSUE THREAD

**Issue by windo** [online-go/gtp2ogs#172] opened 2019-03-06 22:14 UTC
I was contacted by Eugene (ogs staff) that one of amybot games had gotten stuck. Looking at logs, I recalled having seen this before, too. So filing a bug in case someone else sees something like this.

In this game, the bot thought it made a move:

```
Mar 06 09:19:12   bot.js:140                     [26756] <<< = D11
Mar 06 09:19:12   game.js:484                    [Game 16869954]  Move 44   Playing d11 { x: 3, y: 8, text: 'd11', resign: false, pass: false }
```

But server does not respond. The next message about the game in logs is:

```
Mar 06 09:21:13   connection.js:1696             #  Dumping status of all connected games
...
Mar 06 09:21:13   connection.js:1696             #  game_id=16869954: black=amybot-ddk white=SimplyOrnate bot_turn idle_time=124.823s bot.proc.pid=26756 bot.dead=false bot.failed=false
Mar 06 09:21:13   connection.js:1696             #  Dump complete
```

A little while later the human resigns, to get out of the game. I can find a few other examples of this happening in the logs too.

**Comment by windo** [comment] 2019-03-06 22:18
In `game.js`, the log message and sending the move are right one after another:

```
if (config.DEBUG) this.log("Playing " + move.text, move);
else this.log("Playing " + move.text);
this.socket.emit('game/move', this.auth({
    'game_id': this.game_id,
    'move': encodeMove(move)
}));
```

So I can't imagine how we could have not sent the move. So either the move was not accepted or something. I think I'll try to work around this by disconnecting and reconncting. But seems weird, like possibly a server issue.

@anoek, @roy7, wdyt?

**Comment by windo** [comment] 2019-03-06 22:45
Whaat, looking at one of those games, it looks like `gtp2ogs` asked the bot to play twice.

I'll better check that none of my unmerged changes are not doing anything fishy here...

**Comment by roy7** [comment] 2019-03-06 23:15
This is another problem I've never had in the  old code base so either it was your custom code or brand new problem with server. I suspect user error? Other operators I don't think ever reported this.

**Comment by roy7** [comment] 2019-03-07 00:42
Long long ago I had an issue about not knowing whose turn it was so sometimes I tried to move on wrong turn and bot got into board states that didn't match server. An illegal move will silently fail. Look at your game log and compare to OGS. Maybe you told bot to move twice and so it had stones in wrong place, leading to eventual illegal move.

**Comment by roy7** [comment] 2019-03-07 01:02
Important thought, at some point I had the issue that trying to kill the bots might still allow it to finish running, which means the genmove it was doing still arrives via stdin. And then I'd process that move even through I'm trying to restart the bot to move again. I think I eventually solve it by closing the stdin socket connection when deciding to kill the bot process. If anything you changed related to bot crashing and restarting maybe isn't closing the pipe, that's something to look at. It might be that sending a 'quit' is after a genmove is already under way, meaning you'll still get the play result before bot exits.

**Comment by windo** [comment] 2019-03-07 08:31
Yep, something like that (illegal moves) is definitely happening.

Good point about closing the stdin/stdout - I'll add that, too.

**Comment by roy7** [comment] 2019-03-07 14:35
Looking at the code again that's why the 'ignore' flag was added in there, which it appears you do still have. I have to believe something in your bot-restart related changes must be putting you in a situation where you are trying to restart the bot but end up reading the prior bot genmove result for processing anyway.

**Comment by windo** [comment] 2019-03-07 14:37
It happened several times on gtp2ogs restart - so on the first start of a bot. But maybe that's just where I noticed it the most because I would check the logs after restarting gtp2ogs...

**Comment by roy7** [comment] 2020-05-24 19:08
Perhaps this was caused by an extra gamedata generating an extra genmove command, all of which should be fixed not. If not, I'll close issue anyway due to age.

**Closed by roy7** 2020-05-24 19:08 UTC

**Comment by wonderingabout** [comment] 2020-05-24 19:18
> Perhaps this was caused by an extra gamedata generating an extra genmove command, all of which should be fixed not. If not, I'll close issue anyway due to age.

you mean all of this should be fixed now :)
