### ISSUE TITLE
maxconnectedgames limiting games

### ISSUE THREAD

**Issue by windo** [online-go/gtp2ogs#138] opened 2019-02-20 10:01 UTC
I just noticed this and haven't had time to look into it, but I noticed my bot wasn't playing games and was rejecting new games with:

```
Feb 20 09:57:29   connection.js:1658             #  Rejecting challenge from SaMSUoM (24k)  [9x9]  id = 16660150
ESC[36mFeb 20 09:57:29   connection.js:1671             POST online-go.com 443 /api/v1/me/challenges/4556566 { delete: true,
  message: 'Currently, 390 games are being played by this bot, maximum is 20 (if you see this message and you dont see any game on the bot profile page
, it is because private game(s) are being played) , try again later ',
```

While the beginner bot can have quite a few games going on at times, I'm pretty sure there are not 390 ongoing games.

**Comment by windo** [comment] 2019-02-20 10:19
I wonder if `disconnectFromGame` somehow does not manage to properly delete from `this.connected_games` though it seems to be doing it pretty explicitly...

**Comment by wonderingabout** [comment] 2019-02-20 12:39
i doubt that you can really have 390 connected games, your bot profile page would never be able to load @windo 

this suggest that there is some unintended behaviour that should be fixed :+1:

**Comment by roy7** [comment] 2019-02-20 13:39
Perhaps you can add a debugging line every time a challenge comes in to print the # it thinks is there and maybe the list of game IDs or something? That might help isolate where/why/how the # is increasing, or see if a single gameID is being duplicated too many times in connected_games[] somehow.

Maybe we need to check the status of the games as well that the state isn't finished, although I thought finished games get explicitly deleted from connected_games.

This reminds me how my corr queue counter kept going up too high and I finally solved it by making it a flag instead of a counter (I think). A hackish work around. ;)

**Comment by roy7** [comment] 2019-02-20 13:40
Or maybe at the location the reject fires, print a Stringify dump of the entire connecting_games list?

**Comment by windo** [comment] 2019-02-23 08:21
It seems there is a bug in idle games disconnection. I don't know if it's an issue with deleting from the connected_games map while iterating over it or method binding or maybe something trivial that I'm not seeing.

I managed to fix it by doing something like this:

```
for (let game_id in this.connected_games) {
    let state = this.connected_games[game_id].state;
    let idle_time = now - state.clock.last_move;
    if ((state.clock.current_player != this.bot_id) && (idle_time > config.timeout)) {
        idle.push(game_id);
    }
    for (let i in idle) {
        this.disconnectFromGame(idle[i]);
    }
}
```

But I don't know which part of this did the trick. I'll send a change a PR when I figure out how to distill this down into a fix.

**Comment by wonderingabout** [comment] 2019-02-23 08:24
this is very nice @windo 
i just started to learn arrays, so i can understand this code lol :+1: 

big thank you :+1:

**Comment by windo** [comment] 2019-02-23 12:46
Haha, figured it out. It was a very silly bug from my idle game timeout PR. When the server disconnnects, idle game processing stops. Will send a PR to fix that.

**Closed** 2019-02-23 14:05 UTC
